In [39]:
import pandas as pd

In [40]:
file = "Resources_movie_scores.csv"

In [41]:
file_df = pd.read_csv(file, encoding="ISO-8859-1")

In [42]:
file_df.head()

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.3,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.0,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5
2,Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.5,...,3.90,4.0,4.5,3.0,4.0,4.0,627,103660,12055,0.5
3,Do You Believe? (2015),18,84,22,4.7,5.4,5.0,4.5,0.90,4.2,...,2.70,1.0,4.0,1.0,2.5,2.5,31,3136,1793,0.5
4,Hot Tub Time Machine 2 (2015),14,28,29,3.4,5.1,3.5,3.0,0.70,1.4,...,2.55,0.5,1.5,1.5,1.5,2.5,88,19560,1021,0.5

In [43]:
df = file_df.set_index("FILM")
imdb_df = df.loc[:, ["IMDB", "IMDB_norm", "IMDB_norm_round", "IMDB_user_vote_count", ]]
imdb_df.head()

,IMDB,IMDB_norm,IMDB_norm_round,IMDB_user_vote_count
FILM,,,,
Avengers: Age of Ultron (2015),7.8,3.90,4.0,271107
Cinderella (2015),7.1,3.55,3.5,65709
Ant-Man (2015),7.8,3.90,4.0,103660
Do You Believe? (2015),5.4,2.70,2.5,3136
Hot Tub Time Machine 2 (2015),5.1,2.55,2.5,19560

In [44]:
only_good_df = imdb_df.loc(imdb_df["IMDB"] >= 7)
only_good_df.head()

TypeError: 'Series' objects are mutable, thus they cannot be hashed